/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type BanControllerGetBannedUsersParams = {
/**
 * Page number for pagination (default: 1, max: 1000)
 */
page?: number;
/**
 * Number of items per page for pagination (default: 20, max: 100)
 */
limit?: number;
};
