/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { BannedUserItemDto } from "./bannedUserItemDto";

export interface BannedUsersListResponseDto {
  /** List of banned users */
  bannedUsers: BannedUserItemDto[];
  /** Total count of banned users */
  total: number;
  /** Total number of pages */
  totalPages: number;
  /** Current page number */
  currentPage: number;
  /** Number of items per page */
  limit: number;
}
