/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { BlockItemDtoBlockedUserAvatarUrl } from './blockItemDtoBlockedUserAvatarUrl';
import type { BlockItemDtoReason } from './blockItemDtoReason';

export interface BlockItemDto {
  /** Blocked user ID */
  id: string;
  /** ID of the user who performed the block */
  blockerId: string;
  /** ID of the blocked user */
  blockedId: string;
  /** Name of the blocked user */
  blockedUserName: string;
  /**
     * Avatar URL of the blocked user
     * @nullable
     */
  blockedUserAvatarUrl: BlockItemDtoBlockedUserAvatarUrl;
  /** Timestamp when the block was created */
  blockedAt: string;
  /**
     * Reason for blocking
     * @nullable
     */
  reason: BlockItemDtoReason;
}
