/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type ChatControllerGetConversationsParams = {
  /**
   * Cursor for pagination (optional)
   * @nullable
   */
  cursor: string | null;
  /**
   * Number of conversations to return (optional, default: 20)
   * @minimum 1
   * @maximum 50
   */
  limit: number;
};
