/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { DiscoveryUserItemDtoBio } from './discoveryUserItemDtoBio';
import type { DiscoveryUserItemDtoLastSeen } from './discoveryUserItemDtoLastSeen';
import type { DiscoveryUserItemDtoNationality } from './discoveryUserItemDtoNationality';
import type { GalleryItemResponseDto } from './galleryItemResponseDto';

export interface DiscoveryUserItemDto {
  /** Unique identifier of the user */
  id: string;
  /** Name of the user */
  name: string;
  /** Faculty the user belongs to */
  faculty: string;
  /**
     * Nationality of the user
     * @nullable
     */
  nationality: DiscoveryUserItemDtoNationality;
  /**
     * Short bio of the user
     * @nullable
     */
  bio: DiscoveryUserItemDtoBio;
  /**
     * Last seen timestamp of the user
     * @nullable
     */
  lastSeen: DiscoveryUserItemDtoLastSeen;
  /** Gallery images of the user */
  gallery: GalleryItemResponseDto[];
}
