/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type DiscoveryControllerGetDiscoveryParams = {
/**
 * Cursor for pagination (user ID)
 */
cursor?: string;
/**
 * Number of users to return
 * @minimum 1
 * @maximum 10
 */
limit?: number;
};
