/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { GalleryItemResponseDto } from "./galleryItemResponseDto";

export interface DiscoveryUserItemDto {
  /** Unique identifier of the user */
  id: string;
  /** Name of the user */
  name: string;
  /** Faculty the user belongs to */
  faculty: string;
  /**
   * Nationality of the user
   * @nullable
   */
  nationality: string | null;
  /**
   * Short bio of the user
   * @nullable
   */
  bio: string | null;
  /**
   * Last seen timestamp of the user
   * @nullable
   */
  lastSeen: string | null;
  /** Gallery images of the user */
  gallery: GalleryItemResponseDto[];
}
