/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { MatchItemDto } from './matchItemDto';
import type { MatchListResponseDtoNextCursor } from './matchListResponseDtoNextCursor';

export interface MatchListResponseDto {
  matches: MatchItemDto[];
  /**
     * Cursor for pagination
     * @nullable
     */
  nextCursor: MatchListResponseDtoNextCursor;
}
