/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

export type NotificationsControllerGetNotificationsParams = {
/**
 * Cursor for pagination (notification ID)
 */
cursor?: string;
/**
 * Number of notifications to return
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
