/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */

/**
 * Bio
 * @nullable
 */
export type PrivateProfileResponseDtoBio = { [key: string]: unknown } | null;
