/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { GalleryItemResponseDto } from './galleryItemResponseDto';
import type { PrivateProfileResponseDtoAvatarUrl } from './privateProfileResponseDtoAvatarUrl';
import type { PrivateProfileResponseDtoBio } from './privateProfileResponseDtoBio';
import type { PrivateProfileResponseDtoBirthYear } from './privateProfileResponseDtoBirthYear';
import type { PrivateProfileResponseDtoFaculty } from './privateProfileResponseDtoFaculty';
import type { PrivateProfileResponseDtoInterestsItem } from './privateProfileResponseDtoInterestsItem';
import type { PrivateProfileResponseDtoMaxPreferredAge } from './privateProfileResponseDtoMaxPreferredAge';
import type { PrivateProfileResponseDtoMinPreferredAge } from './privateProfileResponseDtoMinPreferredAge';
import type { PrivateProfileResponseDtoNationality } from './privateProfileResponseDtoNationality';
import type { PrivateProfileResponseDtoPreferredFacultiesItem } from './privateProfileResponseDtoPreferredFacultiesItem';
import type { PrivateProfileResponseDtoPreferredGender } from './privateProfileResponseDtoPreferredGender';
import type { PrivateProfileResponseDtoPreferredNationalitiesItem } from './privateProfileResponseDtoPreferredNationalitiesItem';

export interface PrivateProfileResponseDto {
  /** User ID */
  id: string;
  /** Email */
  email: string;
  /** Name */
  name: string;
  /**
     * Avatar URL
     * @nullable
     */
  avatarUrl: PrivateProfileResponseDtoAvatarUrl;
  /**
     * Bio
     * @nullable
     */
  bio?: PrivateProfileResponseDtoBio;
  /** Gender */
  gender: string;
  /**
     * Faculty
     * @nullable
     */
  faculty?: PrivateProfileResponseDtoFaculty;
  /**
     * Nationality
     * @nullable
     */
  nationality?: PrivateProfileResponseDtoNationality;
  /** Interests */
  interests: PrivateProfileResponseDtoInterestsItem[];
  /**
     * Birth year
     * @nullable
     */
  birthYear?: PrivateProfileResponseDtoBirthYear;
  /**
     * Minimum preferred age
     * @nullable
     */
  minPreferredAge?: PrivateProfileResponseDtoMinPreferredAge;
  /**
     * Maximum preferred age
     * @nullable
     */
  maxPreferredAge?: PrivateProfileResponseDtoMaxPreferredAge;
  /** Preferred gender */
  preferredGender: PrivateProfileResponseDtoPreferredGender;
  /** Preferred nationalities */
  preferredNationalities: PrivateProfileResponseDtoPreferredNationalitiesItem[];
  /** Preferred faculties */
  preferredFaculties: PrivateProfileResponseDtoPreferredFacultiesItem[];
  /** User gallery items */
  gallery: GalleryItemResponseDto[];
}
