/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { GalleryItemResponseDto } from "./galleryItemResponseDto";
import type { PublicUserProfileDtoFaculty } from "./publicUserProfileDtoFaculty";
import type { PublicUserProfileDtoGender } from "./publicUserProfileDtoGender";
import type { PublicUserProfileDtoInterestsItem } from "./publicUserProfileDtoInterestsItem";
import type { PublicUserProfileDtoNationality } from "./publicUserProfileDtoNationality";

export interface PublicUserProfileDto {
  /** User ID */
  id: string;
  /** Name */
  name: string;
  /**
   * Avatar URL
   * @nullable
   */
  avatarUrl: string | null;
  /**
   * Bio
   * @nullable
   */
  bio: string | null;
  /** Gender */
  gender: PublicUserProfileDtoGender;
  /**
   * Faculty
   * @nullable
   */
  faculty: PublicUserProfileDtoFaculty;
  /**
   * Nationality
   * @nullable
   */
  nationality: PublicUserProfileDtoNationality;
  /** Interests */
  interests: PublicUserProfileDtoInterestsItem[];
  /**
   * Birth year
   * @nullable
   */
  birthYear: number | null;
  /** User gallery items */
  gallery: GalleryItemResponseDto[];
  /** Indicates if the user is matched */
  isMatched: boolean;
  /** Indicates if the user is online */
  isOnline: boolean;
  /**
   * Last online timestamp
   * @nullable
   */
  lastOnline: string | null;
}
