/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * KBU Connect API
 * Exclusive dating platform for KBU students
 * OpenAPI spec version: 1.0
 */
import type { UserSummaryDtoAvatarUrl } from './userSummaryDtoAvatarUrl';

export interface UserSummaryDto {
  /** User ID */
  id: string;
  /** User name */
  name: string;
  /**
     * Avatar URL
     * @nullable
     */
  avatarUrl: UserSummaryDtoAvatarUrl;
}
